[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false